### ISSUE TITLE
Is it true that an json property can be both an array or object based on the value?

### ISSUE THREAD

**Issue by nbijl-worthit** [EiffelWebFramework/HAL#8]
Hi, 
I'm building a client that is build on the Eiffel HAL library.
Let's say I got this call: 
GET/order/1
returning: 
```json
{
  "order_id": 1,
  "items": [
    { 
      "product_id": 1, 
      "amount": 1, 
    },
    { 
      "product_id": 2, 
      "amount": 1, 
    }
   ]
}
```

But when there is only one object in the items collection, then it shows as: 
```json
{
  "order_id": 1,
  "items": 
    { 
      "product_id": 1, 
      "amount": 1, 
    }
}
```

Is that correct? Should it not be consistent? 
Is this because it uses the so called ["smart_serialization"](https://github.com/eiffelhub/json/blob/c69f1083fc04a73e6a15d3f8d190875e5370b947/library/serialization/json_serialization_factory.e)? Can we change it to always return an array when it finds a collection?

Thanks!!

**Comment by jocelyn** [comment]
Hi,

I have just tried with a small example, and I have the expected JSON.
I am not able to reproduce your issue.
In addition, it is weird, as your JSON is not valid neither as there should be not `,` after  the `"amount":1` text.

Can you share a small example to reproduce your issue?
Also, can you precise which version of EiffelStudio you are using.

**Comment by nbijl-worthit** [comment]
Hi @jocelyn 
I just type the JSON by hand, so it might be true that it's not valid. Is was just a showcase ;-)

I'll send this ticket to the developer on the API side (I'm one of the developers on the client side)

> I am not able to reproduce your issue.
You mean that you always see an array with objects, even if there is just one ?

Thanks,

**Comment by gokkeppayplaza** [comment]
Hi Jocelyn,

Nico is part of the team using the API's we have written.
We had some discussion about the hal_json specifications considering the above.

I have investigated the HAL library for this, and it seems that when a HAL+JSON representation has to be made and the internal embedded resources are to be converted to JSON, there is a check in the code if the count of the resources is 1, and the result of the check results in the use of a json array or not. See following code snippet where this code is in:

```
	to_json_embedded_resource_internal (a_resource: LIST [HAL_RESOURCE]; ctx: JSON_SERIALIZER_CONTEXT): JSON_VALUE
		local
			l_result_arr: JSON_ARRAY
		do
			if a_resource.count = 1 then
				Result := to_json (a_resource.first, ctx)
			else
				create {JSON_ARRAY} l_result_arr.make_empty
				across
					a_resource as ic
				loop
					if attached to_json (ic.item, ctx) as l_iter then
						l_result_arr.add (l_iter)
					end
				end
				Result := l_result_arr
			end
		end
```
The HAL+JSON specification is noting the following:

4.1.  Reserved Properties
 
4.1.1.  _links
 
   The reserved "_links" property is OPTIONAL.
 
   It is an object whose property names are link relation types (as
   defined by [RFC5988]) and values are either a Link Object or an array
   of Link Objects.  The subject resource of these links is the Resource
   Object of which the containing "_links" object is a property.
 
4.1.2.  _embedded
 
   The reserved "_embedded" property is OPTIONAL
 
   It is an object whose property names are link relation types (as
   defined by [RFC5988]) and values are either a Resource Object or an
   array of Resource Objects.
 
   Embedded Resources MAY be a full, partial, or inconsistent version of
   the representation served from the target URI.

Somehow it seems to be common sense to not have this distinction between 1 or more embedded resources and just always use an array?

Another solution would be to do this optionally?

Can you please share your opinion about this?
Is it possible that this is changed in a new version?

Best regards,

Paul Gokke (PayPlaza)

**Comment by jvelilla** [comment]
Hi Nico and Paul

The current behavior was based on others open source implementations of HAL(http://phlyrestfully.readthedocs.io/en/latest/halprimer.html, ), since a  `_embedded` property can be either a resource or an array of resources. 

But as Paul point is ok to always use the option of always return an `array of resources`.
I will work on it and pull a new version ASAP.
/Javier

**Comment by jvelilla** [comment]
Updated code to always use `array of resources`
